### ISSUE TITLE
Add support for an equals(...) method

### ISSUE THREAD

**Issue by tghamm** [castle-it/sharp2Js#2]
It would be nice if there were an `$equals(..)` method that could be created optionally per type and defined in the parser settings, similar to the `$merge(...)` method.

Ideally you compare the value of each property as defined by the passed in `PropertyBag` collection and parser options.  It should test failure and return quickly where possible.  It should handle deep collection comparison as well as custom class comparison using the `euqls(...) method internally.

**Comment by tqheel** [comment]
This is a test comment. Hopefully it will show up in Slack channel. Booya.
